### ISSUE TITLE
Wiki cluttered with ads

### ISSUE THREAD

**Issue by yagonax** [Netflix/netflix-graph#17]
Hi team,
I suspect someone got wiki write rights, and added a large number of ads pages to the wiki with names such as "service pemanas air 081288408887".
It might be worth reviewing active permissions for this repo and removing undesired pages.
Meanwhile, I'll read the one which are not ads ;)
Thanks is advance
Aurelien

**Comment by dkoszewnik** [comment]
Hi Aurelien,

Thanks for the heads up.  We've removed the spam and restricted wiki update permissions to Netflix.

Thanks again,
Drew.
