### ISSUE TITLE
Add a link for the Kotlin wrapper?

### ISSUE THREAD

**Issue by apatrida** [Netflix/netflix-graph#25]
I have published this Kotlin wrapper that does a lot with Netflix-graph if you want to link to it.

https://github.com/klutter/klutter/tree/master/netflix-graph

Is on maven central from version `0.1.1` of [Klutter](https://github.com/klutter/klutter) onwards.

**Comment by dkoszewnik** [comment]
Added to the wiki.  Thank you!
